apiVersion: batch/v1
kind: Job
metadata:
  name: tsc003-beat-move-files
  namespace: cyberarch

spec:
  template:
    spec:
      containers:
        - name: work-container
          image: tsekai/a2bs_withpip:latest # docker image
          # imagePullPolicy: Always
          command:
                - bash
                - -c
                - |
                  source /usr/local/bin/_activate_current_env.sh
                  rsync -avAXEWSlHh /tsc003-beat-vol/audio2pose/ /tsc003-gesturegen-vol/ --no-compress --info=progress2
          resources:
            requests:
              cpu: "10"
              memory: "10Gi"
              #nvidia.com/gpu: "1"
              ephemeral-storage: 50Gi

            limits:
              cpu: "10"
              memory: "10Gi"
              #nvidia.com/gpu: "1"
              ephemeral-storage: 50Gi
          volumeMounts:
            # - name: data
            #   mountPath: /data
            - name: tsc003-gesturegen-vol
              mountPath: /tsc003-gesturegen-vol
            - name: tsc003-beat-vol
              mountPath: /tsc003-beat-vol
      volumes:
        # - name: data
        #   emptyDir: {}
        - name: tsc003-gesturegen-vol
          persistentVolumeClaim:
            claimName: tsc003-gesturegen-vol
        - name: tsc003-beat-vol
          persistentVolumeClaim:
            claimName: tsc003-beat-vol
      # nodeSelector:
      #   nautilus.io/disktype: nvme
      restartPolicy: Never
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #         - matchExpressions:
      #           - key: nvidia.com/gpu.product
      #             operator: In
      #             values:
      #               - NVIDIA-GeForce-RTX-3090