apiVersion: v1
kind: Pod
metadata:
  name: tsc003-test
  namespace: cyberarch

spec:
  containers:
    - name: work-container
      image: tsekai/a2bs_withpip:latest # docker image
      # imagePullPolicy: Always
      command:
            - bash
            - -c
            - |
              source /usr/local/bin/_activate_current_env.sh
              cd /cyberarch/gesturegen/audio2pose
              git pull
              echo "done setup"
              sleep infinity
      resources:
        requests:
          cpu: "10"
          memory: "20Gi"
          nvidia.com/gpu: "1"
          ephemeral-storage: 50Gi

        limits:
          cpu: "10"
          memory: "20Gi"
          nvidia.com/gpu: "1"
          ephemeral-storage: 50Gi
      volumeMounts:
        # - name: data
        #   mountPath: /data
        - name: cyberarch
          mountPath: /cyberarch
  volumes:
    # - name: data
    #   emptyDir: {}
    - name: cyberarch
      persistentVolumeClaim:
        claimName: cyberarch
  nodeSelector:
    nautilus.io/disktype: nvme
  restartPolicy: Never
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: nvidia.com/gpu.product
              operator: In
              values:
                - NVIDIA-GeForce-RTX-3090