apiVersion: v1
kind: Pod
metadata:
  name: tsc003-test
  namespace: cyberarch

spec:
  containers:
    - name: work-container
      image: tsekai/a2bs_withpip:latest # docker image
      # imagePullPolicy: Always
      command:
            - bash
            - -c
            - |
              source /usr/local/bin/_activate_current_env.sh
              echo "done setup"
              sleep infinity
      resources:
        requests:
          cpu: "10"
          memory: "20Gi"
          nvidia.com/gpu: "1"
          # ephemeral-storage: 100Gi

        limits:
          cpu: "10"
          memory: "20Gi"
          nvidia.com/gpu: "1"
          # ephemeral-storage: 100Gi
      volumeMounts:
        # - name: data
        #   mountPath: /data
        - name: tsc003-beat-vol
          mountPath: /tsc003-beat-vol
  volumes:
    # - name: data
    #   emptyDir: {}
    - name: tsc003-beat-vol
      persistentVolumeClaim:
        claimName: tsc003-beat-vol
  # nodeSelector:
  #   nautilus.io/disktype: nvme
  restartPolicy: Never
  # affinity:
  #   nodeAffinity:
  #     requiredDuringSchedulingIgnoredDuringExecution:
  #       nodeSelectorTerms:
  #         - matchExpressions:
  #           - key: nvidia.com/gpu.product
  #             operator: In
  #             values:
  #               - NVIDIA-GeForce-RTX-3090