is_train: True 
out_root_path: /outputs/audio2pose/ 
train_data_path: /datasets/beat_cache/beat_4english_15_141/train/ 
val_data_path: /datasets/beat_cache/beat_4english_15_141/val/ 
test_data_path: /datasets/beat_cache/beat_4english_15_141/test/ 
mean_pose_path: /datasets/beat_cache/beat_4english_15_141/train/
std_pose_path: /datasets/beat_cache/beat_4english_15_141/train/
torch_hub_path: /datasets/hub/checkpoints/ 
e_path:  /datasets/beat_cache/beat_4english_15_141/weights/ae_300.bin
test_ckpt: /datasets/beat_cache/beat_4english_15_141/weights/camn.bin
dataset: beat
new_cache: False
audio_rep: wave16k
facial_rep: facial52
speaker_id: id
pose_rep: bvh_rot
word_rep: text
sem_rep: sem
emo_rep: emo
freeze_wordembed: False
speaker_dims: 30
facial_dims: 51
pose_dims: 141
word_f: 0
emotion_f: 8
speaker_f: 8
audio_f: 128
facial_f: 32
word_index_num: 11247
word_dims: 300
batch_size: 256
no_adv_epoch: 200
hidden_size: 256
model: camn
g_name: CaMN
d_name: ConvDiscriminator
eval_model: motion_autoencoder
e_name: HalfEmbeddingNet
vae_length: 300
rec_weight: 500
adv_weight: 0.1
trainer: camn
kld_weight: 0.0
div_reg_weight: 0.0
grad_norm: 200
epochs: 100
test_period: 99