is_train: True 
out_root_path: /outputs/audio2pose/ 
train_data_path: /datasets/beat_cache/beat_4english_15_141/train/ 
val_data_path: /datasets/beat_cache/beat_4english_15_141/val/ 
test_data_path: /datasets/beat_cache/beat_4english_15_141/test/ 
mean_pose_path: /datasets/beat_cache/beat_4english_15_141/train/
std_pose_path: /datasets/beat_cache/beat_4english_15_141/train/
torch_hub_path: /datasets/hub/checkpoints/ 
e_path:  /datasets/beat_cache/beat_4english_15_141/weights/ae_300.bin
test_ckpt: /datasets/beat_cache/beat_4english_15_141/weights/multi.bin
vae_length: 300
dataset: beat
new_cache: False
freeze_wordembed: False
pose_rep: bvh_rot
audio_rep: wave16k
word_rep: text
speaker_id: True
audio_norm: True
sem_rep: sem
pose_length: 34
stride: 10
pose_dims: 141
audio_f: 128
word_f: 128
word_index_num: 5793
word_dims: 300
facial_dims: 51
speaker_dims: 30
speaker_f: 8
batch_size: 256
no_adv_epoch: 10
hidden_size: 256
g_name: PoseGenerator
d_name: ConvDiscriminator
model: multi_context_net
eval_model: motion_autoencoder
e_name: HalfEmbeddingNet
rec_weight: 500
adv_weight: 0.5
trainer: multi
kld_weight: 0.1
div_reg_weight: 0.01
epochs: 100
test_period: 99